# Generated by Django 3.1.3 on 2020-11-19 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shorts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='code',
            field=models.CharField(default=shorts.models.generate_code, max_length=8),
        ),
    ]
